### DISCUSSION TITLE
Improve the extension color theming configuration

### DISCUSSION THREAD

**Discussion by azzamsa** [kamiyaa/joshuto#362] [Ideas]
I want to have diverse colors and extensions.

My sources of inspiration are:
- https://github.com/sharkdp/vivid/blob/master/config/filetypes.yml
- https://github.com/sharkdp/vivid/blob/master/themes/dracula.yml

Porting them to Joshuto needs a bit of work.

```toml
[ext]

#
# Text  [orange: rgb(255, 184, 108)]
#

# specia
CONTRIBUTORS.fg = "rgb(255, 184, 108)"
CONTRIBUTORS.md.fg = "rgb(255, 184, 108)"
CONTRIBUTORS.txt.fg = "rgb(255, 184, 108)"
INSTALL.fg = "rgb(255, 184, 108)"
INSTALL.md.fg = "rgb(255, 184, 108)"
INSTALL.txt.fg = "rgb(255, 184, 108)"
README.fg = "rgb(255, 184, 108)"
README.md.fg = "rgb(255, 184, 108)"
README.txt.fg = "rgb(255, 184, 108)"

# todo
TODO.fg = "rgb(255, 184, 108)"
TODO.md.fg = "rgb(255, 184, 108)"
TODO.txt.fg = "rgb(255, 184, 108)"

# licenses
COPYING.fg = "rgb(255, 184, 108)"
COPYRIGHT.fg = "rgb(255, 184, 108)"
LICENSE.fg = "rgb(255, 184, 108)"
LICENSE-APACHE.fg = "rgb(255, 184, 108)"
LICENSE-MIT.fg = "rgb(255, 184, 108)"

#
# Text - Configuration [orange: rgb(255, 184, 108)]
#

# generic
cfg.fg = "rgb(255, 184, 108)"
conf.fg = "rgb(255, 184, 108)"
config.fg = "rgb(255, 184, 108)"
ini.fg = "rgb(255, 184, 108)"
json.fg = "rgb(255, 184, 108)"
tml.fg = "rgb(255, 184, 108)"
toml.fg = "rgb(255, 184, 108)"
yaml.fg = "rgb(255, 184, 108)"
yml.fg = "rgb(255, 184, 108)"

# metadata
xmp.fg = "rgb(255, 184, 108)"

# bibtex
bib.fg = "rgb(255, 184, 108)"
bst.fg = "rgb(255, 184, 108)"

# dockerfile
Dockerfile.fg = "rgb(255, 184, 108)"

# nix
nix.fg = "rgb(255, 184, 108)"

# qt
ui.fg = "rgb(255, 184, 108)"

# desktop
desktop.fg = "rgb(255, 184, 108)"

# system
passwd.fg = "rgb(255, 184, 108)"
shadow.fg = "rgb(255, 184, 108)"

# other
txt.fg = "rgb(255, 184, 108)"

#
# Text - Markup [orange: rgb(255, 184, 108)]
#

# web
htm.fg = "rgb(255, 184, 108)"
html.fg = "rgb(255, 184, 108)"
shtml.fg = "rgb(255, 184, 108)"
xhtml.fg = "rgb(255, 184, 108)"

# other
csv.fg = "rgb(255, 184, 108)"
markdown.fg = "rgb(255, 184, 108)"
md.fg = "rgb(255, 184, 108)"
mdown.fg = "rgb(255, 184, 108)"
org.fg = "rgb(255, 184, 108)"
rst.fg = "rgb(255, 184, 108)"
xml.fg = "rgb(255, 184, 108)"

#
# programming [orange: rgb(255, 184, 108)]
#

# rust
rs.fg = "rgb(255, 184, 108)"

# javascript:
js.fg = "rgb(255, 184, 108)"
htc.fg = "rgb(255, 184, 108)"

# shell
sh.fg = "rgb(255, 184, 108)"
bash.fg = "rgb(255, 184, 108)"
zsh.fg = "rgb(255, 184, 108)"
fish.fg = "rgb(255, 184, 108)"

#
# Media (pink: rgb(255, 121, 198))
#

# Images
bmp.fg = "rgb(255, 121, 198)"
eps.fg = "rgb(255, 121, 198)"
gif.fg = "rgb(255, 121, 198)"
ico.fg = "rgb(255, 121, 198)"
jpeg.fg = "rgb(255, 121, 198)"
jpg.fg = "rgb(255, 121, 198)"
pbm.fg = "rgb(255, 121, 198)"
pgm.fg = "rgb(255, 121, 198)"
png.fg = "rgb(255, 121, 198)"
ppm.fg = "rgb(255, 121, 198)"
psd.fg = "rgb(255, 121, 198)"
svg.fg = "rgb(255, 121, 198)"
tif.fg = "rgb(255, 121, 198)"
tiff.fg = "rgb(255, 121, 198)"
webp.fg = "rgb(255, 121, 198)"
xcf.fg = "rgb(255, 121, 198)"

# Audio
aif.fg = "rgb(255, 121, 198)"
ape.fg = "rgb(255, 121, 198)"
flac.fg = "rgb(255, 121, 198)"
m3u.fg = "rgb(255, 121, 198)"
m4a.fg = "rgb(255, 121, 198)"
mid.fg = "rgb(255, 121, 198)"
mp3.fg = "rgb(255, 121, 198)"
ogg.fg = "rgb(255, 121, 198)"
opus.fg = "rgb(255, 121, 198)"
wav.fg = "rgb(255, 121, 198)"
wma.fg = "rgb(255, 121, 198)"
wv.fg = "rgb(255, 121, 198)"

# Video
avi.fg = "rgb(255, 121, 198)"
flv.fg = "rgb(255, 121, 198)"
h264.fg = "rgb(255, 121, 198)"
m4v.fg = "rgb(255, 121, 198)"
mkv.fg = "rgb(255, 121, 198)"
mov.fg = "rgb(255, 121, 198)"
mp4.fg = "rgb(255, 121, 198)"
mpeg.fg = "rgb(255, 121, 198)"
mpg.fg = "rgb(255, 121, 198)"
rm.fg = "rgb(255, 121, 198)"
swf.fg = "rgb(255, 121, 198)"
vob.fg = "rgb(255, 121, 198)"
webm.fg = "rgb(255, 121, 198)"
wmv.fg = "rgb(255, 121, 198)"

# Font
fnt.fg = "rgb(255, 121, 198)"
fon.fg = "rgb(255, 121, 198)"
otf.fg = "rgb(255, 121, 198)"
ttf.fg = "rgb(255, 121, 198)"
woff.fg = "rgb(255, 121, 198)"

#
# Office [orange: rgb(255, 184, 108)]
#

# document
doc.fg = "rgb(255, 184, 108)"
docx.fg = "rgb(255, 184, 108)"
epub.fg = "rgb(255, 184, 108)"
odt.fg = "rgb(255, 184, 108)"
pdf.fg = "rgb(255, 184, 108)"
ps.fg = "rgb(255, 184, 108)"
rtf.fg = "rgb(255, 184, 108)"
sxw.fg = "rgb(255, 184, 108)"

# spreadsheet
xls.fg = "rgb(255, 184, 108)"
xlsx.fg = "rgb(255, 184, 108)"
ods.fg = "rgb(255, 184, 108)"
xlr.fg = "rgb(255, 184, 108)"

# presentation
ppt.fg = "rgb(255, 184, 108)"
pptx.fg = "rgb(255, 184, 108)"
odp.fg = "rgb(255, 184, 108)"
sxi.fg = "rgb(255, 184, 108)"
kex.fg = "rgb(255, 184, 108)"
pps.fg = "rgb(255, 184, 108)"

# calendar
ics.fg = "rgb(255, 184, 108)"

#
# Archive [red: rgb(255, 85, 85))]
#

# Packages
apk.fg = "rgb(255, 85, 85)"
deb.fg = "rgb(255, 85, 85)"
rpm.fg = "rgb(255, 85, 85)"
xbps.fg = "rgb(255, 85, 85)"

# images
bin.fg = "rgb(255, 85, 85)"
dmg.fg = "rgb(255, 85, 85)"
img.fg = "rgb(255, 85, 85)"
iso.fg = "rgb(255, 85, 85)"
toast.fg = "rgb(255, 85, 85)"
vcd.fg = "rgb(255, 85, 85)"

# other
7z.fg = "rgb(255, 85, 85)"
arj.fg = "rgb(255, 85, 85)"
bz.fg = "rgb(255, 85, 85)"
bz2.fg = "rgb(255, 85, 85)"
gz.fg = "rgb(255, 85, 85)"
jar.fg = "rgb(255, 85, 85)"
pkg.fg = "rgb(255, 85, 85)"
rar.fg = "rgb(255, 85, 85)"
tar.fg = "rgb(255, 85, 85)"
tbz.fg = "rgb(255, 85, 85)"
tbz2.fg = "rgb(255, 85, 85)"
tgz.fg = "rgb(255, 85, 85)"
xz.fg = "rgb(255, 85, 85)"
z.fg = "rgb(255, 85, 85)"
zip.fg = "rgb(255, 85, 85)"
zst.fg = "rgb(255, 85, 85)"

#
# executable [green: rgb(80, 250, 123)]
#

# windows
bat.fg = "rgb(80, 250, 123)"
com.fg = "rgb(80, 250, 123)"
exe.fg = "rgb(80, 250, 123)"

# library
so.fg = "rgb(80, 250, 123)"
a.fg = "rgb(80, 250, 123)"
dll.fg = "rgb(80, 250, 123)"

# linux
ko.fg = "rgb(80, 250, 123)"

#
# Unimportant [comment: rgb(98, 114, 164)]
#

# build_artifacts
# cxx
o.fg = "rgb(98, 114, 164)"
la.fg = "rgb(98, 114, 164)"
lo.fg = "rgb(98, 114, 164)"

# cmake
CMakeCache.txt.fg = "rgb(98, 114, 164)"

# automake
in.fg = "rgb(98, 114, 164)"

# rust
rlib.fg = "rgb(98, 114, 164)"

# python
pyc.fg = "rgb(98, 114, 164)"
pyd.fg = "rgb(98, 114, 164)"
pyo.fg = "rgb(98, 114, 164)"

# haskell
dyn_hi.fg = "rgb(98, 114, 164)"
dyn_o.fg = "rgb(98, 114, 164)"
cache.fg = "rgb(98, 114, 164)"
hi.fg = "rgb(98, 114, 164)"

# java
class.fg = "rgb(98, 114, 164)"

# scons
scons_opt.fg = "rgb(98, 114, 164)"
sconsign.dblite.fg = "rgb(98, 114, 164)"

# latex
aux.fg = "rgb(98, 114, 164)"
bbl.fg = "rgb(98, 114, 164)"
bcf.fg = "rgb(98, 114, 164)"
blg.fg = "rgb(98, 114, 164)"
fdb_latexmk.fg = "rgb(98, 114, 164)"
fls.fg = "rgb(98, 114, 164)"
idx.fg = "rgb(98, 114, 164)"
ilg.fg = "rgb(98, 114, 164)"
ind.fg = "rgb(98, 114, 164)"
out.fg = "rgb(98, 114, 164)"
sty.fg = "rgb(98, 114, 164)"
synctex.gz.fg = "rgb(98, 114, 164)"
toc.fg = "rgb(98, 114, 164)"

# llvm
bc.fg = "rgb(98, 114, 164)"
bak.fg = "rgb(255, 121, 198)"
git.fg = "rgb(255, 121, 198)"
lock.fg = "rgb(255, 121, 198)"
log.fg = "rgb(255, 121, 198)"
orig.fg = "rgb(255, 121, 198)"
pid.fg = "rgb(255, 121, 198)"
swp.fg = "rgb(255, 121, 198)"
tmp.fg = "rgb(255, 121, 198)"
"package-lock.json".fg = "rgb(255, 121, 198)"
```

Anyway, We still have some issues.

- Can we use a variable for each color, to avoid repetition?
- Can we define the exact file name, not the extension?
- Can we group them like this https://github.com/sharkdp/vivid/blob/89e7fe37190051719ee7bfa11e0377b5e0e32515/config/filetypes.yml#L47, and theming them such this https://github.com/sharkdp/vivid/blob/89e7fe37190051719ee7bfa11e0377b5e0e32515/themes/dracula.yml#L106. So it is easier to port to other future format. and possibly have user-contributed theme.

Thanks for Joshuto :heart:
