### DISCUSSION TITLE
Fish Shell: How to quit into the current directory

### DISCUSSION THREAD

**Discussion by cleissonalves** [kamiyaa/joshuto#578] [Show and tell]
### 1. Using a keymap (The simple method)

Add the keymap to `~/.config/joshuto/keymap.toml`. You can change the key if you want. I used `x`.

```toml
[default_view]

keymap = [
  #...
  { keys = ["x"], commands = ["shell fish"] },
  #...
]
```

#### Add joshuto funtion alias(Optional)

First create the file `j.fish` inside the directory `~/.config/fish/functions`.

Add the following content to the file and save it.

```fish
function j
    command joshuto $argv
end
```

The name of the file and the name of the function must be the same. 

This name will be used to run joshuto in the terminal.  In my example, I used `j`.

So, to run joshuto in the terminal i just type:

```bash
j
```

And to exit into the current directory, i press:

```
x
```

### 2. Using a function (a little more complicated)

First create the file `j.fish` inside the directory `~/.config/fish/functions`.

Add the following content to the file and save it.

```fish
function j
    set OUTPUT_FILE (mktemp -t "joshuto-cwd.XXXXXX")

    env joshuto --output-file $OUTPUT_FILE $argv
    set exit_code $status

    switch $exit_code
        case 0
            # Regular exit
            # No action needed
        case 101
            # Output contains current directory
            set JOSHUTO_CWD (cat $OUTPUT_FILE)
            cd $JOSHUTO_CWD
        case 102
            # Output selected files
            # No action needed
        case '*'
            echo "Exit code: $exit_code"
    end
end
```

The name of the file and the name of the function must be the same. 

This name will be used to run joshuto in the terminal. 

In my example, I used `j`.

So, to run joshuto in the terminal i just type:

```bash
j
```

Check the keymap that exits joshuto with `quit --output-current-directory` in the `~/.config/joshuto/keymap.toml`.

The default is:

```toml
[default_view]

keymap = [
  #...
  { keys = ["Q"], commands = ["quit --output-current-directory"] },
  #...
]
```

You can change the key if you want.

Then when exiting joshuto with this key, the fish shell will use the current directory.
