### ISSUE TITLE
So it looks like `termion` (the library that `joshuto` uses for input), it only supports Ctrl/Alt + a character https://docs.rs/termion/latest/termion/event/enum.Key.html

### ISSUE THREAD

**Issue by alexzanderr** [kamiyaa/joshuto#189]
So it looks like `termion` (the library that `joshuto` uses for input), it only supports Ctrl/Alt + a character https://docs.rs/termion/latest/termion/event/enum.Key.html

So Ctrl+arrow_up/arrow_down is currently not supported 

https://gitlab.redox-os.org/redox-os/termion/-/issues/194

https://gitlab.redox-os.org/redox-os/termion/-/merge_requests/175

_Originally posted by @kamiyaa in https://github.com/kamiyaa/joshuto/issues/186#issuecomment-1193335622_

**Comment by alexzanderr** [comment]
```toml
# ~/.config/joshuto/keymap.toml

[default_view]
keymap = [
	{ keys = [ "ctrl+arrow_up"], command = "preview_cursor_move_up" },
	{ keys = [ "ctrl+arrow_down"], command = "preview_cursor_move_down" },
```
this config doesnt work and results in a message at runtime such as:
```shell
❱  cargo run --all-features
   Compiling joshuto v0.9.4 (...)
    Finished dev [unoptimized + debuginfo] target(s) in 4.73s
     Running `target/debug/joshuto`
Error: Keybindings ambiguous for preview_cursor_move_down
```
