### ISSUE TITLE
Weird sequences in preview

### ISSUE THREAD

**Issue by on3iro** [kamiyaa/joshuto#364]
Hey,

I just installed joshuto and the preview script. Standalone the preview-script is working fine, seemingly using bat to preview most of my text files. However, when used in conjunction with joshuto, the output looks as follows:

![image](https://github.com/kamiyaa/joshuto/assets/8681413/3a790457-a82d-41b8-b7ec-5656ba3e89b3)

Here's my config:

```toml
numbered_command = false

use_trash = false
watch_files = true
xdg_open = false
xdg_open_fork = false


[display]
# default, hsplit
mode = "default"

automatically_count_files = false
collapse_preview = true
# ratios for parent view (optional), current view and preview
column_ratio = [1, 4, 4]
scroll_offset = 6
show_borders = true
show_hidden = true
show_icons = true
tilde_in_titlebar = true
# none, absolute, relative
line_number_style = "relative"

[display.sort]
# lexical, mtime, natural, size, ext
sort_method = "natural"
case_sensitive = true
directories_first = true
reverse = false

[preview]
max_preview_size = 2097152                           # 2MB
preview_script = "~/.config/joshuto/preview_file.sh" # make sure it's marked as executable

[tab]
# inherit, home, root
home_page = "home"   
```

I'm on OSX, if that matters

Any idea what I could be doing wrong?

Thanks in advance!
