### ISSUE TITLE
open file in vim (same window)

### ISSUE THREAD

**Issue by bashfulrobot** [kamiyaa/joshuto#394]
This is more of a question.

The behaviour that I am looking for is:

- navigate to a file
- if the appropriate file type opens in Neovim, replace Johuto in the same terminal
- when saving, or exiting the file, return to Joshuto

Is this possible?

Right now, when I open the file, it pops a new terminal but does not seem to be using my Neovim settings, etc.

Thank you.

**Comment by Akmadan23** [comment]
Make sure that in your `mimetype.toml` you have something like this
```toml
[class]

text = [
  { command = "nvim" }
]
```
and not
```toml
[class]

text = [
  { command = "nvim", fork = true }
]
```
so that neovim will replace joshuto instead of spawning a new window.
