### ISSUE TITLE
mime-type is stuck for the defined case

### ISSUE THREAD

**Issue by DearRude** [kamiyaa/joshuto#397]
When, the following extention is assigned:
`jpg."inherit" = "image_default";`
The expected functionality is all files with different cases such as `.JPG` or `.Jpg` be assigned to `image_default` too.

However only defined case is assgined to the respective mime.

**Comment by kamiyaa** [comment]
Yes, `joshuto` is case sensitive.

A solution to this is to just have a mimetype option set instead of an extension option:


```toml
[mimetype]

[mimetype.image]
inherit = "image_default"
```
