### ISSUE TITLE
Control modifier for keymaps

### ISSUE THREAD

**Issue by cjbassi** [kamiyaa/joshuto#4]
Is there currently a way to do this? Didn't see any examples of it or anything related to it in the `keymap.rs` file.

**Comment by kamiyaa** [comment]
No, I have yet to find a way to implement this.

**Comment by kamiyaa** [comment]
This has been implemented in the dev branch.
However, to keep it simple, the configurations is now more complicated:
```toml
# old
[[mapcommand]]
keys = [ "p", "p" ]
command = "paste_files"

# new
[[mapcommand]]
keys = [ 112, 112 ]
command = "paste_files"

[[mapcommand]]
keys = [ 20 ]        # equivalent to Ctrl+T
command = "new_tab"
```
Now it makes use of ascii values because there is a difference between Ctrl+key and key by itself.
I chose to do this as it is much simpler to parse. Rather than having to have defined string values in the program that maps string to i32 and worrying about parsing `Ctrl+...`
