### ISSUE TITLE
`[selection.prefix]` not working?

### ISSUE THREAD

**Issue by xfzv** [kamiyaa/joshuto#403]
With only `~/.config/joshuto/theme.toml`:

```toml
[selection.prefix]
prefix = "* "    # or any other character than "*"
size = 2
```

I'm just getting a space when selecting an item with `<space>` instead of the character set in `prefix`:

![1](https://github.com/kamiyaa/joshuto/assets/78810647/325264f3-a9a6-441c-8836-9c718607d915)

I tried with an empty `~/.config/kitty` directory just to make sure it wasn't due to my terminal theme but it doesn't make any difference. Likewise, changing `size` value doesn't do anything.

joshuto was built with `❯ cargo build --release`, from 3141bd24c31d9ca9419c109e7f89bdb009e3b5bc (latest commit on the `main` branch as I'm writing this).

**Comment by kamiyaa** [comment]
Interesting, I will look into it. I do remember not fully implementing this feature.

**Comment by kamiyaa** [comment]
Fixed in 18221047b833d3c2ede82f2959fc8a4c39da5591
Feel free to re-open if it's still not working

Usage:
```toml
[selection]
fg = "light_yellow"
bold = true
prefix = " "
```
