### ISSUE TITLE
How to open external app detached?

### ISSUE THREAD

**Issue by domeniczz** [kamiyaa/joshuto#596]
For example, openning a pdf file, joshuto will launch e.g. zathura. But zathura is not launched in detached mode. When I quit joshuto, zathura will also quit.

Do joshuto support launch application in detached mode?

Below is part of my joshuto.toml:

```toml
numbered_command = false
mouse_support = true
focus_on_create = true
use_trash = true
watch_files = true
xdg_open = true
xdg_open_fork = true
case_insensitive_ext = false
zoxide_update = false
```
