### ISSUE TITLE
Spawn commands executed with ":shell"

### ISSUE THREAD

**Issue by DLFW** [kamiyaa/joshuto#69]
When using a command with :shell, like 
```toml
[[mapcommand]]
command = "shell sxiv -t %s &>/dev/null &"
keys = [ "i" ]
```
joshuto waits for the process to terminate at `command.status()?;` in `shell.rs`.

For many use cases, this is pretty unhandy. Instead of using a blocking sub-process call, joshuto could just spawn the sub-process with `command.spawn()?;` instead.

Alternatively, joshuto could use two shell commands, one blocking and one non-blocking. (I could take that.)
